import fs from 'node:fs';import assert from 'node:assert/strict';import {createRequire} from 'node:module';
const root=process.cwd()+'/';fs.mkdirSync('test-output',{recursive:true});const require=createRequire(root+'package.json');const ts=require('typescript');
for(const name of ['music','xml']){const source=fs.readFileSync(root+'lib/'+name+'.ts','utf8');let js=ts.transpileModule(source,{compilerOptions:{module:ts.ModuleKind.ESNext,target:ts.ScriptTarget.ES2022}}).outputText.replace("'./music'","'./music.mjs'");fs.writeFileSync('test-output/'+name+'.mjs',js)}
const {KEYS,transpose,toABC,validate,parsePitch,interval,shiftChord}=await import('../test-output/music.mjs');const {fromXML,toXML}=await import('../test-output/xml.mjs');const sample=JSON.parse(fs.readFileSync(root+'lib/sample.json'));const {JSDOM}=require('jsdom');const dom=new JSDOM('<!DOCTYPE html><html><body><div id="score"></div></body></html>');globalThis.window=dom.window;globalThis.document=dom.window.document;globalThis.DOMParser=dom.window.DOMParser;Object.defineProperty(globalThis,'navigator',{value:dom.window.navigator,configurable:true});
const original=JSON.stringify(sample);assert.equal(sample.measures.length,27);assert.deepEqual(validate(sample),[]);
for(const target of KEYS){const shifted=transpose(sample,'A',target);assert.deepEqual(validate(shifted),[]);shifted.measures.forEach((m,i)=>m.notes.forEach((n,j)=>{const prev=sample.measures[i].notes[j];if(n.pitch!=='R')assert.equal(parsePitch(n.pitch).midi-parsePitch(prev.pitch).midi,interval('A',target).semi);assert.equal(n.duration,prev.duration);assert.equal(n.lyric,prev.lyric);assert.equal(n.tie,prev.tie)}));const back=transpose(shifted,target,'A');assert.deepEqual(back.measures,sample.measures);const xml=toXML(shifted),round=fromXML(xml);assert.deepEqual(round.measures.map(m=>m.notes),shifted.measures.map(m=>m.notes));}
assert.equal(JSON.stringify(sample),original);for(const [a,b] of [['A','G'],['E','D'],['D2','C2'],['F#m','Em'],['E/G#','D/F#'],['D/E','C/D']])assert.equal(shiftChord(a,'A','G'),b);
const abc=toABC(transpose(sample,'A','G'));assert.ok(!abc.split('K:G\n')[1].replace(/"[^"]*"/g,'').match(/[_^=]/),'Diatonic sample must not repeat key accidentals');assert.ok(abc.includes('z G GG'),'First single eighth and original pairs');
const accidentalTest={title:'test',key:'G',meter:'4/4',measures:[{number:1,notes:['F#4','F4','F4','F#4'].map(pitch=>({pitch,duration:1,tie:false,lyric:'',chord:''}))},{number:2,notes:[{pitch:'F#4',duration:4,tie:false,lyric:'',chord:''}]}]};const text=toABC(accidentalTest);assert.ok(text.includes('F2 =F2 F2 ^F2'));assert.ok(text.includes('| F8'));
const abcjs=require('abcjs');dom.window.SVGElement.prototype.getBBox=function(){const text=this.textContent||'';const size=parseFloat(this.getAttribute('font-size')||'14');return {x:0,y:0,width:text.length*size*.65,height:size*1.2}};
const tunes=abcjs.renderAbc('score',abc,{staffwidth:730,paddingleft:28,paddingright:28,paddingtop:24,paddingbottom:20,add_classes:true});assert.ok(!tunes[0].warnings?.length,JSON.stringify(tunes[0].warnings));const svg=dom.window.document.querySelector('svg');assert.ok(svg);assert.ok(svg.querySelectorAll('.abcjs-beam-elem').length>10);fs.writeFileSync('test-output/score-G.svg',new dom.window.XMLSerializer().serializeToString(svg));fs.writeFileSync('test-output/score-G.musicxml',toXML(transpose(sample,'A','G')));fs.writeFileSync('test-output/score-G.abc',abc);
console.log(JSON.stringify({keysTested:KEYS.length,measures:27,notes:sample.measures.flatMap(m=>m.notes).filter(n=>n.pitch!=='R').length,beamGroups:svg.querySelectorAll('.abcjs-beam-elem').length,abcWarnings:tunes[0].warnings??[],xmlRoundTrip:'passed',transposition:'passed',keyAccidentals:'passed'},null,2));
