export type Note={pitch:string;duration:number;tie:boolean;lyric:string;chord:string;beam?:string};
export type Measure={number:number;notes:Note[];sourcePage?:number;lineStart?:boolean;repeatStart?:boolean;repeatEnd?:boolean;ending?:string;endingStop?:boolean};
export type Score={title:string;key:string;meter:string;sourcePageCount?:number;credit?:string;copyright?:string;provenance?:string;measures:Measure[]};
export const KEYS=['C','C#','Db','D','Eb','E','F','F#','Gb','G','Ab','A','Bb','B'];
const letters='CDEFGAB', naturals=[0,2,4,5,7,9,11];
export const fifths:Record<string,number>={C:0,'C#':7,Db:-5,D:2,Eb:-3,E:4,F:-1,'F#':6,Gb:-6,G:1,Ab:-4,A:3,Bb:-2,B:5};
export function parsePitch(p:string){const m=/^([A-G])([#b]*)(-?\d+)?$/.exec(p);if(!m)throw Error('音高格式應為 A4、F#4 或 Bb4');const letter=letters.indexOf(m[1]);const accidental=[...m[2]].reduce((a,c)=>a+(c==='#'?1:-1),0);const octave=Number(m[3]??4);return {letter,octave,midi:12*(octave+1)+naturals[letter]+accidental};}
export function interval(from:string,to:string){const raw= parsePitch(to).midi-parsePitch(from).midi;let semi=((raw+18)%12)-6;if(semi===-6&&raw>0)semi=6;let dia=(letters.indexOf(to[0])-letters.indexOf(from[0])+7)%7;if(semi<0&&dia>0)dia-=7;if(semi===0)dia=letters.indexOf(to[0])-letters.indexOf(from[0]);return {semi,dia};}
export function shiftPitch(p:string,from:string,to:string,withOctave=true){if(p==='R')return p;const q=parsePitch(p), d=interval(from,to), idx=q.octave*7+q.letter+d.dia, octave=Math.floor(idx/7),letter=((idx%7)+7)%7, a=q.midi+d.semi-(12*(octave+1)+naturals[letter]);return letters[letter]+(a>0?'#'.repeat(a):'b'.repeat(-a))+(withOctave?octave:'');}
export function shiftChord(chord:string,from:string,to:string){if(!chord)return '';const m=/^([A-G][#b]*)([^/]*)(?:\/([A-G][#b]*))?$/.exec(chord);if(!m)throw Error('和弦格式不正確：'+chord);return shiftPitch(m[1],from,to,false)+m[2]+(m[3]?'/'+shiftPitch(m[3],from,to,false):'');}
export function transpose(score:Score,from:string,to:string):Score{return {...score,key:to,measures:score.measures.map(m=>({...m,notes:m.notes.map(n=>({...n,pitch:shiftPitch(n.pitch,from,to),chord:shiftChord(n.chord,from,to)}))}))};}
const clean=(s:string)=>s.replace(/[\r\n"\\]/g,' ');
function abcPitch(p:string,key:string,accidentals:Map<string,number>){if(p==='R')return 'z';const m=/^([A-G])([#b]*)(-?\d+)$/.exec(p)!;const oct=Number(m[3]);const count=fifths[key];const order=count>0?'FCGDAEB':'BEADGCF';const keyAlter=order.slice(0,Math.abs(count)).includes(m[1])?(count>0?1:-1):0;const desired=[...m[2]].reduce((a,c)=>a+(c==='#'?1:-1),0);const identity=m[1]+oct;const current=accidentals.get(identity)??keyAlter;const prefix=desired===current?'':desired===0?'=':desired>0?'^'.repeat(desired):'_'.repeat(-desired);accidentals.set(identity,desired);return prefix+(oct>=5?m[1].toLowerCase():m[1])+(oct>5?"'".repeat(oct-5):oct<4?','.repeat(4-oct):'');}
export function toABC(s:Score){let result=`X:1\nT:${clean(s.title)}\nC:${clean(s.credit??'')}\nM:${s.meter}\nL:1/8\n%%staffwidth 730\n%%pagewidth 810\n%%leftmargin 28\n%%rightmargin 28\n%%titlefont serif 22\n%%vocalfont sans-serif 14\n%%gchordfont sans-serif 15\n%%staffsep 50\n%%musicspace 16\n%%measurenb 0\nK:${s.key}\n`;let music='',words:string[]=[];
const flush=()=>{if(music){result+=music+'\n';if(words.some(x=>x!=='*'))result+='w: '+words.join(' ')+'\n';music='';words=[];}};
s.measures.forEach((m,i)=>{if(m.lineStart&&i>0)flush();if(m.repeatStart)music+='|: ';if(m.ending)music+='['+m.ending+' ';let beat=0;const accidentals=new Map<string,number>();m.notes.forEach((n,j)=>{const duration=n.duration*2;music+=(n.chord?'"'+clean(n.chord)+'"':'')+abcPitch(n.pitch,s.key,accidentals)+(duration===1?'':duration)+(n.tie?'-':'');beat+=n.duration;if(n.beam?n.beam==='end'||n.beam==='none':beat%1===0)music+=' ';if(n.pitch!=='R')words.push(n.lyric?clean(n.lyric).replace(/ /g,'~'):'*');});music+=m.repeatEnd?':| ':i===s.measures.length-1?'|] ':m.endingStop?'|| ':'| ';});flush();return result;}
export function validate(s:Score){let issues:string[]=[];const [beats,unit]=s.meter.split('/').map(Number);for(const m of s.measures){const total=m.notes.reduce((a,n)=>a+n.duration,0);if(Math.abs(total-beats*4/unit)>.001)issues.push(`第 ${m.number} 小節：${total} 拍（應為 ${beats*4/unit}）`);for(const n of m.notes){if(n.pitch!=='R')parsePitch(n.pitch);shiftChord(n.chord,s.key,s.key);if(![.25,.5,.75,1,1.5,2,3,4].includes(n.duration))issues.push(`第 ${m.number} 小節：不支援的時值`);}}return issues;}
