import {Score,Note,Measure,KEYS,fifths,parsePitch} from './music';
const esc=(s:string)=>s.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&apos;'}[c]!));
export function toXML(s:Score){const [beats,beatType]=s.meter.split('/');let out=`<?xml version="1.0" encoding="UTF-8"?><score-partwise version="4.0"><work><work-title>${esc(s.title)}</work-title></work><identification><creator type="composer">${esc(s.credit??'')}</creator><rights>${esc(s.copyright??'')}</rights></identification><part-list><score-part id="P1"><part-name>旋律</part-name></score-part></part-list><part id="P1">`;let previousTie=false;
for(const [i,m] of s.measures.entries()){out+=`<measure number="${m.number}">`+(i&&m.sourcePage&&m.sourcePage!==(s.measures[i-1].sourcePage??1)?'<print new-page="yes"/>':m.lineStart&&i?'<print new-system="yes"/>':'');if(!i)out+=`<attributes><divisions>4</divisions><key><fifths>${fifths[s.key]}</fifths></key><time><beats>${beats}</beats><beat-type>${beatType}</beat-type></time><clef><sign>G</sign><line>2</line></clef></attributes>`;if(m.repeatStart||m.ending)out+='<barline location="left">'+(m.ending?`<ending number="${m.ending}" type="start"/>`:'')+(m.repeatStart?'<repeat direction="forward"/>':'')+'</barline>';
for(const n of m.notes){if(n.chord){const c=/^([A-G])([#b]*)([^/]*)(?:\/([A-G])([#b]*))?$/.exec(n.chord)!;const alter=(a:string)=>[...a].reduce((v,c)=>v+(c==='#'?1:-1),0);let kind=c[3]==='m'?'minor':c[3]==='7'?'dominant':c[3]==='maj7'?'major-seventh':c[3]==='m7'?'minor-seventh':c[3]==='2'?'suspended-second':!c[3]?'major':'other';out+=`<harmony><root><root-step>${c[1]}</root-step><root-alter>${alter(c[2])}</root-alter></root><kind text="${esc(c[3])}">${kind}</kind>${c[4]?`<bass><bass-step>${c[4]}</bass-step><bass-alter>${alter(c[5]??'')}</bass-alter></bass>`:''}</harmony>`;}
const durationTypes:Record<number,[string,boolean]>={.25:['16th',false],.5:['eighth',false],.75:['eighth',true],1:['quarter',false],1.5:['quarter',true],2:['half',false],3:['half',true],4:['whole',false]};const [type,dot]=durationTypes[n.duration]??['quarter',false];let pitch='<rest/>';if(n.pitch!=='R'){const p=parsePitch(n.pitch);const natural=[0,2,4,5,7,9,11][p.letter];pitch=`<pitch><step>${'CDEFGAB'[p.letter]}</step><alter>${p.midi-(p.octave+1)*12-natural}</alter><octave>${p.octave}</octave></pitch>`;}const stop=previousTie&&n.pitch!=='R';out+=`<note>${pitch}<duration>${n.duration*4}</duration>${stop?'<tie type="stop"/>':''}${n.tie?'<tie type="start"/>':''}<type>${type}</type>${dot?'<dot/>':''}${n.beam&&n.beam!=='none'?`<beam number="1">${n.beam}</beam>`:''}${stop||n.tie?'<notations>'+(stop?'<tied type="stop"/>':'')+(n.tie?'<tied type="start"/>':'')+'</notations>':''}${n.lyric?`<lyric><syllabic>single</syllabic><text>${esc(n.lyric)}</text></lyric>`:''}</note>`;previousTie=n.tie;}
if(m.repeatEnd||m.endingStop||i===s.measures.length-1)out+='<barline location="right">'+(m.endingStop?`<ending number="${m.ending||'1'}" type="${m.repeatEnd?'stop':'discontinue'}"/>`:'')+(m.repeatEnd?'<repeat direction="backward"/>':i===s.measures.length-1?'<bar-style>light-heavy</bar-style>':'')+'</barline>';out+='</measure>';}
return out+'</part></score-partwise>';}
export function fromXML(xml:string):Score{const doc=new DOMParser().parseFromString(xml,'application/xml');if(doc.querySelector('parsererror'))throw Error('樂譜資料格式損壞');const parts=doc.querySelectorAll('score-partwise > part');if(parts.length!==1)throw Error('第一版僅支援單一旋律聲部，請先匯出單聲部樂譜。');let divisions=1,key='C',meter='4/4',sourcePage=1;const measures:Measure[]=[];
for(const [i,m] of Array.from(parts[0].children).filter(x=>x.tagName==='measure').entries()){if(m.querySelector('backup, note > chord, note > grace, time-modification'))throw Error('此譜含多聲部、倚音或連音群，超出第一版支援範圍。');if(i&&m.querySelector('print[new-page="yes"]'))sourcePage++;if(m.querySelector('forward, note > unpitched')||Array.from(m.querySelectorAll('harmony > offset')).some(x=>Number(x.textContent)!==0))throw Error(`第 ${i+1} 小節含尚未支援的時間偏移或無音高音符。`);const mode=m.querySelector('key > mode')?.textContent;if(mode&&mode!=='major')throw Error('目前僅支援大調旋律譜。');const d=m.querySelector('divisions');if(d)divisions=Number(d.textContent);const f=m.querySelector('key > fifths');if(f){const newKey=KEYS.find(k=>fifths[k]===Number(f.textContent));if(!newKey)throw Error('不支援的調號');if(i&&newKey!==key)throw Error(`第 ${i+1} 小節有中途轉調，目前請分段處理。`);key=newKey;}const time=m.querySelector('time');if(time){const newMeter=`${time.querySelector('beats')?.textContent}/${time.querySelector('beat-type')?.textContent}`;if(i&&newMeter!==meter)throw Error(`第 ${i+1} 小節有拍號變更，目前請分段處理。`);meter=newMeter;}let pending='',notes:Note[]=[];
for(const e of Array.from(m.children)){if(e.tagName==='harmony'){const acc=(v:string|null|undefined)=>Number(v)>0?'#'.repeat(Number(v)):'b'.repeat(-Number(v||0));const root=e.querySelector('root-step')?.textContent??'';const kind=e.querySelector('kind');const suffix=kind?.getAttribute('text')??({minor:'m',dominant:'7','major-seventh':'maj7','minor-seventh':'m7','suspended-second':'2'}[kind?.textContent??'']??'');const bass=e.querySelector('bass-step')?.textContent;pending=root+acc(e.querySelector('root-alter')?.textContent)+suffix+(bass?'/'+bass+acc(e.querySelector('bass-alter')?.textContent):'');}else if(e.tagName==='note'){const p=e.querySelector('pitch');const a=Number(p?.querySelector('alter')?.textContent??0);notes.push({pitch:p?(p.querySelector('step')!.textContent!+(a>0?'#'.repeat(a):'b'.repeat(-a))+p.querySelector('octave')!.textContent):'R',duration:Number(e.querySelector('duration')?.textContent??0)/divisions,tie:!!e.querySelector('tie[type="start"]'),chord:pending,beam:e.querySelector('beam[number="1"]')?.textContent??'none',lyric:e.querySelector('lyric > text')?.textContent??''});pending='';}}
const ending=m.querySelector('ending[type="start"]');measures.push({number:i+1,notes,sourcePage,lineStart:i===0||!!m.querySelector('print[new-system="yes"], print[new-page="yes"]'),repeatStart:!!m.querySelector('repeat[direction="forward"]'),repeatEnd:!!m.querySelector('repeat[direction="backward"]'),ending:ending?.getAttribute('number')??'',endingStop:!!m.querySelector('ending[type="stop"], ending[type="discontinue"]')});}
if(!measures.length||measures.length>1000)throw Error('請使用 1–1000 小節的旋律譜。');return {title:doc.querySelector('work-title')?.textContent||'上傳的旋律譜',key,meter,sourcePageCount:sourcePage,credit:doc.querySelector('creator')?.textContent??'',copyright:doc.querySelector('rights')?.textContent??'',measures,provenance:'本機 Audiveris 自動辨識，尚未校對。'};}
